### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/bower-files#1]
Overview: a library that will talk to bower and grab all of the files that you need for your app.

Usage:

```
var bowerFiles = require('bower-files');

bowerFiles(function(err, files) {
//array of all file paths, in order by dependency
//example that includes weekly
//files => ['/path/to/jquery.js', '/path/to/fidel.js', ..., '/path/to/weekly']
})

//just include filetype css (default: type: .js)
bowerFiles({ type: '.css' }, function(err, files) {});

//just grab deps for weekly
bowerFiles({ include: 'weekly', function(err, files) {
});

//grab all deps except jquery
bowerFiles({ exclude: 'jquery', function(err, files) {
});
```

some of the work is already done here: https://github.com/jgallen23/grunt-concat-bower/blob/master/tasks/concat_bower.js.

make sure it has tests

**Comment by Antonio-Laguna** [comment]
Should `err` be populated at some point? Or just fail silently?

**Comment by jgallen23** [comment]
err could be if you try to include something that doesn't exist

**Comment by Antonio-Laguna** [comment]
Ok!

What happens if your dependencies doesn't have any main and hence, you fail getting the file?

**Comment by jgallen23** [comment]
hmm.  I think it should error.  We should add support to pass in main files if the bower.json doesn't have it
