### ISSUE TITLE
Cli tool

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/bower-files#2]

**Comment by Antonio-Laguna** [comment]
Right now is just outputting it to the console, can you think on any other uses of this?

**Comment by jgallen23** [comment]
how is it outputting?  json or just new line?

**Comment by Antonio-Laguna** [comment]
Just console.log the array  or throwing the error

## 

Sent from my mobile device

**Comment by jgallen23** [comment]
I think by default it should console log each file on a new line or pass in --json to output it as json
